FROM ubuntu:focal

USER root

SHELL [ "/bin/bash", "-c" ]

RUN apt update && \
    apt install -y --no-install-recommends \
    python3 \
    python3-dev \
    python3-venv \
    python3-distutils \
    build-essential

RUN cd /home && \
    mkdir venvs && \
    python3 -m venv venvs/openqa-app

WORKDIR /home/app

COPY ./backend .

RUN source /home/venvs/openqa-app/bin/activate && \
    pip install -U pip && \
    pip install -r requirements.txt

CMD /home/venvs/openqa-app/bin/python app.py